### ISSUE TITLE
omrdatasettools issues

### ISSUE THREAD

**Issue by RyanChomistek** [apacha/MusicSymbolClassifier#1]
I have recently discovered that some of the URLs in omrdatasettools  v.8 are now dead. I was able to update all of the downloaders except the fornes one to use the latest omrdatasettools.

Also I found that the training test validation split was really imbalanced since some classes have vastly more classes than others

**Comment by apacha** [comment]
Hi Ryan,
thanks for pointing this out. Indeed the URLs are dead, because I moved all datasets to [Github](https://github.com/apacha/OMR-Datasets/releases/tag/datasets) in order to make them permanently available. Previously they were stored in my private ownCloud account that could get shut down at any point, while now they are safely mirrored at Github. All the URLs for downloading them have been updated in the newest version of the `omrdatasettools`, which is now also updated in this repository.

As for the train/test/validation split class-imbalance: Yes, that can be indeed a problem. You can add weights to individual classes or restrict yourself to dataset, that are more balanced, such as the HOMUS dataset.

I hope this helps.
